package ru.workinprogress.booblik.net.client

import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertFalse
import kotlin.test.assertTrue

/**
 * The partitioner, checked on **every** target.
 *
 * The full table lives in `conformance/vectors/partitioner-fnv1a.tsv` and is read by the JVM test
 * beside this one — common code cannot open a file. So a handful of the vectors are inlined here
 * instead, chosen for what they catch rather than for coverage, because "the algorithm agrees with
 * the specification" is a claim about the native builds too and a JVM-only test cannot make it.
 *
 * If these disagree with the TSV, the TSV wins: it is generated by an implementation in another
 * language, and that independence is the whole point.
 */
class PartitionerTest {
    @Test
    fun `the hash matches the golden vectors on this target`() {
        // keyHex to hash, straight out of conformance/vectors/partitioner-fnv1a.tsv.
        val vectors =
            listOf(
                "" to 2166136261u,
                "00" to 84696351u,
                "7f" to 4195109838u,
                // The one that matters: a signed reading of 0x80 gives 83079839 instead, and that
                // is the number both the Kotlin and the Go implementations produced when their
                // masks were removed.
                "80" to 2232128415u,
                "ff" to 2047574606u,
                "757365722d31" to 4115888500u,
            )

        for ((keyHex, expected) in vectors) {
            assertEquals(expected, Partitioner.fnv1a32(hexKey(keyHex)).toUInt(), "hash of «$keyHex»")
        }
    }

    @Test
    fun `the fold matches the golden vectors for three partitions`() {
        val vectors = listOf("" to 1, "00" to 0, "7f" to 0, "80" to 0, "ff" to 2, "757365722d31" to 1)

        for ((keyHex, expected) in vectors) {
            assertEquals(expected, Partitioner.Fnv1a.partitionFor(hexKey(keyHex), 3), "«$keyHex» among 3")
        }
    }

    /**
     * `0x80` must enter the hash as 128 and not as −128. Kotlin's `Byte` is signed, so this is the
     * line that needs `and 0xFF` — and the line every other language's port gets wrong in its own
     * way.
     */
    @Test
    fun `a high byte is read unsigned`() {
        val signExtended = ((0x811C9DC5.toInt() xor 0xFFFFFF80.toInt()) * 0x01000193)
        assertFalse(Partitioner.fnv1a32(byteArrayOf(0x80.toByte())) == signExtended)
    }

    @Test
    fun `the fold never leaves the partition range`() {
        for (partitions in 1..9) {
            for (byte in 0..255) {
                val chosen = Partitioner.Fnv1a.partitionFor(byteArrayOf(byte.toByte()), partitions)
                assertTrue(chosen in 0 until partitions, "$chosen is outside 0..<$partitions")
            }
        }
    }

    /**
     * The superseded partitioner is held to its behaviour too. It exists only to keep reading topics
     * written before 0.3.0, which is a promise about exactly what it computes; a compatibility path
     * nobody checks stops being one quietly.
     */
    @Test
    fun `the pre-0_3_0 partitioner still computes what it used to`() {
        val vectors = listOf("" to 1, "00" to 1, "7f" to 2, "80" to 2, "ff" to 0)

        for ((keyHex, expected) in vectors) {
            assertEquals(
                expected,
                Partitioner.JavaArrayHash.partitionFor(hexKey(keyHex), 3),
                "«$keyHex» among 3",
            )
        }
    }

    private fun hexKey(text: String): ByteArray =
        ByteArray(text.length / 2) { index ->
            val high = "0123456789abcdef".indexOf(text[index * 2])
            val low = "0123456789abcdef".indexOf(text[index * 2 + 1])
            ((high shl 4) or low).toByte()
        }
}
